from __future__ import annotations

from enum import StrEnum


class ReasonCode(StrEnum):
    BASELINE_A = "BASELINE_A"
    RULE_ROUTE = "RULE_ROUTE"
    LOW_CONFIDENCE = "LOW_CONFIDENCE"
    LOW_CONFIDENCE_GATE = "LOW_CONFIDENCE_GATE"
    NO_EXPERT_NEEDED = "NO_EXPERT_NEEDED"
    SLTC_SPIKE = "SLTC_SPIKE"
    SLTC_SUBTHRESHOLD = "SLTC_SUBTHRESHOLD"
    SLTC_FALLBACK_LLM = "SLTC_FALLBACK_LLM"
    SLTC_PLACEHOLDER = "SLTC_PLACEHOLDER"
    CB_OPEN = "CB_OPEN"
    TOOL_BUDGET_EXCEEDED = "TOOL_BUDGET_EXCEEDED"
    RECURSION_DEPTH_EXCEEDED = "RECURSION_DEPTH_EXCEEDED"
    PLANNER_OK = "PLANNER_OK"
    PLANNER_REPAIR_APPLIED = "PLANNER_REPAIR_APPLIED"
    PLANNER_SCHEMA_INVALID = "PLANNER_SCHEMA_INVALID"
    PLANNER_PARSE_FALLBACK = "PLANNER_PARSE_FALLBACK"
    PLANNER_LLM_FAILURE = "PLANNER_LLM_FAILURE"
    EXPERT_NOT_FOUND = "EXPERT_NOT_FOUND"
    EXPERT_SCHEMA_INVALID = "EXPERT_SCHEMA_INVALID"
