from __future__ import annotations

SOURCE_INSTALL_CLAIM_SET = "source-local-install"

SOURCE_INSTALL_TARGET_WITHOUT_EVIDENCE = "SOURCE_INSTALL_TARGET_WITHOUT_EVIDENCE"
SOURCE_INSTALL_TARGET_STALE = "SOURCE_INSTALL_TARGET_STALE"
SOURCE_INSTALL_TARGET_BLOCKED = "SOURCE_INSTALL_TARGET_BLOCKED"
SOURCE_INSTALL_OVERCLAIM = "SOURCE_INSTALL_OVERCLAIM"

RELEASE_CLAIM_ACCURACY_BLOCKERS = {
    SOURCE_INSTALL_TARGET_WITHOUT_EVIDENCE,
    SOURCE_INSTALL_TARGET_STALE,
    SOURCE_INSTALL_TARGET_BLOCKED,
    SOURCE_INSTALL_OVERCLAIM,
}

